#include <iostream>
#include <string>
#include <queue>
#include <deque>
#include <stack>
#include <map>
#include <list>
#include <set>
#include <fstream>
#include <algorithm>
#include <iterator>
#include <vector>
#include <iomanip>
#include <bitset>
#include <limits.h>
#include <cmath>
#include <unordered_map>
#include <numeric>
#include <sstream>
#include <random>
#include <complex>
#include <assert.h> 
#include <functional>

